server:
  port: 8090

spring:
  name: test
  #连接池
  datasource:
    url: jdbc:mysql://wane5tsk.2281.dnstoo.com:5506/musican
    username: musican_f
    password: ljcnnw123
  servlet:
    #上传文件大小限制
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.musican.*.model



