server:
  port: 8090

spring:
  name: test
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.musican.*.model

